---
- name: Build and Deploy WAR to Tomcat using Dynamic Inventory
  hosts: tag_Project_my_web_app
  become: yes

  vars:
    repo_url: "https://github.com/Ashu2356/my-web-app.git"
    local_build_dir: "/tmp/my-web-app"

  tasks:
    - name: Ensure Maven is installed on control node
      package:
        name: maven
        state: present
      delegate_to: localhost

    - name: Clone Git repo on control node
      git:
        repo: "{{ repo_url }}"
        dest: "{{ local_build_dir }}"
        version: main
      delegate_to: localhost

    - name: Build WAR using Maven
      command: mvn clean package -DskipTests
      args:
        chdir: "{{ local_build_dir }}"
      delegate_to: localhost

    - name: Copy WAR to Tomcat webapps on target server
      copy:
        src: "{{ local_build_dir }}/target/my-web-app.war"
        dest: "{{ tomcat_path }}/webapps/my-web-app.war"
        mode: '0644'

    - name: Restart Tomcat
      shell: "{{ tomcat_path }}/bin/shutdown.sh && sleep 5 && {{ tomcat_path }}/bin/startup.sh"

    - name: Verify app is deployed
      uri:
        url: "http://{{ inventory_hostname }}:8080/my-web-app/"
        status_code: 200

